plugins {
    id 'com.android.application'
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "org.denistouch.youtubescreensaver"
        minSdk 31
        targetSdk 32
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
//    implementation 'androidx.leanback:leanback:1.2.0'
    implementation "androidx.tv:tv-material:1.0.1"
//    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:11.1.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
}